import type { FaqItem } from "@/components/FAQ";

export type LanguagePage = {
  slug: string;
  name: string;
  nativeName: string;
  metaTitle: string;
  metaDescription: string;
  heading: string;
  intro: string[];
  faqs: FaqItem[];
};

function buildFaqs(name: string): FaqItem[] {
  return [
    {
      q: `Can I get a ${name} transcript from any YouTube video?`,
      a: `Yes, as long as the video has ${name} captions or subtitles available — either uploaded by the creator or auto-generated by YouTube.`,
    },
    {
      q: `Does the tool translate videos into ${name}?`,
      a: `No, it extracts the ${name} captions that already exist on the video. It doesn't machine-translate transcripts between languages.`,
    },
    {
      q: `Can I download the ${name} transcript?`,
      a: `Yes. You can copy it, or download it as a TXT, timestamped TXT, or SRT subtitle file.`,
    },
  ];
}

export const languages: LanguagePage[] = [
  {
    slug: "spanish",
    name: "Spanish",
    nativeName: "Español",
    metaTitle: "YouTube Transcript Generator in Spanish (Español)",
    metaDescription:
      "Extract Spanish transcripts from YouTube videos for free. Generar transcripciones de YouTube en español al instante.",
    heading: "YouTube Transcript Generator — Spanish",
    intro: [
      "Extract the Spanish transcript from any public YouTube video that has Spanish captions or subtitles, whether uploaded by the creator or auto-generated.",
      "Paste the video URL, and if Spanish captions are available, they'll be pulled directly — no translation, just the original Spanish text ready to copy or download.",
    ],
    faqs: buildFaqs("Spanish"),
  },
  {
    slug: "french",
    name: "French",
    nativeName: "Français",
    metaTitle: "YouTube Transcript Generator in French (Français)",
    metaDescription:
      "Extract French transcripts from YouTube videos for free. Générez des transcriptions YouTube en français instantanément.",
    heading: "YouTube Transcript Generator — French",
    intro: [
      "Extract the French transcript from any public YouTube video that has French captions or subtitles available.",
      "The tool pulls the original French captions directly from YouTube — useful for language learners, students and researchers working with French-language content.",
    ],
    faqs: buildFaqs("French"),
  },
  {
    slug: "german",
    name: "German",
    nativeName: "Deutsch",
    metaTitle: "YouTube Transcript Generator in German (Deutsch)",
    metaDescription:
      "Extract German transcripts from YouTube videos for free. Erstellen Sie kostenlos YouTube-Transkripte auf Deutsch.",
    heading: "YouTube Transcript Generator — German",
    intro: [
      "Extract the German transcript from any public YouTube video with German captions or subtitles.",
      "Whether you're studying German, researching German-language content, or repurposing a German video, get the full text in seconds.",
    ],
    faqs: buildFaqs("German"),
  },
  {
    slug: "hindi",
    name: "Hindi",
    nativeName: "हिन्दी",
    metaTitle: "YouTube Transcript Generator in Hindi",
    metaDescription:
      "Extract Hindi transcripts from YouTube videos for free. YouTube वीडियो से हिंदी ट्रांसक्रिप्ट तुरंत प्राप्त करें।",
    heading: "YouTube Transcript Generator — Hindi",
    intro: [
      "Extract the Hindi transcript from any public YouTube video that has Hindi captions or subtitles available.",
      "Useful for students, researchers and content creators working with Hindi-language YouTube content — get clean, searchable text in seconds.",
    ],
    faqs: buildFaqs("Hindi"),
  },
  {
    slug: "portuguese",
    name: "Portuguese",
    nativeName: "Português",
    metaTitle: "YouTube Transcript Generator in Portuguese (Português)",
    metaDescription:
      "Extract Portuguese transcripts from YouTube videos for free. Gere transcrições do YouTube em português instantaneamente.",
    heading: "YouTube Transcript Generator — Portuguese",
    intro: [
      "Extract the Portuguese transcript from any public YouTube video that has Portuguese captions available, covering both Brazilian and European Portuguese content.",
      "Paste the URL to get the original Portuguese text — no translation involved, just the captions as published.",
    ],
    faqs: buildFaqs("Portuguese"),
  },
  {
    slug: "japanese",
    name: "Japanese",
    nativeName: "日本語",
    metaTitle: "YouTube Transcript Generator in Japanese (日本語)",
    metaDescription:
      "Extract Japanese transcripts from YouTube videos for free. YouTube動画の日本語文字起こしを無料で生成。",
    heading: "YouTube Transcript Generator — Japanese",
    intro: [
      "Extract the Japanese transcript from any public YouTube video that has Japanese captions or subtitles available.",
      "Get searchable Japanese text for study, research or content repurposing without watching the full video.",
    ],
    faqs: buildFaqs("Japanese"),
  },
  {
    slug: "korean",
    name: "Korean",
    nativeName: "한국어",
    metaTitle: "YouTube Transcript Generator in Korean (한국어)",
    metaDescription:
      "Extract Korean transcripts from YouTube videos for free. YouTube 동영상의 한국어 자막을 무료로 추출하세요.",
    heading: "YouTube Transcript Generator — Korean",
    intro: [
      "Extract the Korean transcript from any public YouTube video with Korean captions or subtitles available.",
      "Handy for K-content fans, language learners and researchers who want the text version of a Korean YouTube video.",
    ],
    faqs: buildFaqs("Korean"),
  },
  {
    slug: "arabic",
    name: "Arabic",
    nativeName: "العربية",
    metaTitle: "YouTube Transcript Generator in Arabic (العربية)",
    metaDescription:
      "Extract Arabic transcripts from YouTube videos for free. استخرج نصوص فيديوهات يوتيوب باللغة العربية مجانًا.",
    heading: "YouTube Transcript Generator — Arabic",
    intro: [
      "Extract the Arabic transcript from any public YouTube video that has Arabic captions or subtitles available.",
      "Get the original Arabic text instantly, ready to copy, search or download.",
    ],
    faqs: buildFaqs("Arabic"),
  },
  {
    slug: "italian",
    name: "Italian",
    nativeName: "Italiano",
    metaTitle: "YouTube Transcript Generator in Italian (Italiano)",
    metaDescription:
      "Extract Italian transcripts from YouTube videos for free. Genera trascrizioni YouTube in italiano all'istante.",
    heading: "YouTube Transcript Generator — Italian",
    intro: [
      "Extract the Italian transcript from any public YouTube video that has Italian captions or subtitles.",
      "Paste the video link and get the full Italian text, ready to copy, search or download.",
    ],
    faqs: buildFaqs("Italian"),
  },
  {
    slug: "russian",
    name: "Russian",
    nativeName: "Русский",
    metaTitle: "YouTube Transcript Generator in Russian (Русский)",
    metaDescription:
      "Extract Russian transcripts from YouTube videos for free. Получите текстовую расшифровку видео YouTube на русском.",
    heading: "YouTube Transcript Generator — Russian",
    intro: [
      "Extract the Russian transcript from any public YouTube video that has Russian captions or subtitles available.",
      "Get the full text instantly for study, research or repurposing Russian-language content.",
    ],
    faqs: buildFaqs("Russian"),
  },
];

export function getLanguage(slug: string) {
  return languages.find((l) => l.slug === slug);
}
