import type { Metadata } from "next";
import Link from "next/link";

import Navbar from "@/components/Navbar";
import PSeoHero from "@/components/PSeoHero";
import ContentBlock from "@/components/ContentBlock";
import Features from "@/components/Features";
import HowItWorks from "@/components/HowItWorks";
import FAQ from "@/components/FAQ";
import CTA from "@/components/CTA";
import JsonLd from "@/components/JsonLd";
import Citations from "@/components/Citations";

export const metadata: Metadata = {
  title: "YouTube to Transcript — Free Converter, Accurate Text in Seconds",
  description:
    "Turn any YouTube video into a transcript in seconds. Paste the link, get clean, accurate text back instantly — free, no software, no sign-up required.",
  alternates: { canonical: "/youtube-to-transcript" },
  openGraph: {
    title: "YouTube to Transcript — Free Online Converter",
    description:
      "Paste a YouTube link, get a transcript back instantly. Free, no sign-up.",
    url: "https://www.savefromnet.fun/youtube-to-transcript",
    type: "website",
  },
};

const lastUpdated = "August 2026";

const softwareAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "YouTube to Transcript Converter",
  applicationCategory: "UtilityApplication",
  operatingSystem: "Web",
  url: "https://www.savefromnet.fun/youtube-to-transcript",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
};

const faqs = [
  {
    q: "How do I convert a YouTube video to a transcript?",
    a: "Paste the YouTube video's URL into the box on this page and click Generate. The full transcript is extracted from the video's existing captions in a few seconds — no software or account needed.",
  },
  {
    q: "Is converting YouTube to transcript free?",
    a: "Yes, completely free with no sign-up, no watermark, and no limit on how many videos you convert.",
  },
  {
    q: "What formats can I export the transcript in?",
    a: "You can copy the plain text, or download it as a TXT file, a timestamped TXT file, or an SRT subtitle file — all from the same result.",
  },
  {
    q: "Does this work on any YouTube video?",
    a: "It works on any public YouTube video — including Shorts — as long as the video has captions or subtitles, either added by the creator or auto-generated by YouTube.",
  },
  {
    q: "Why would I convert a YouTube video to text instead of watching it?",
    a: "Text is searchable, skimmable and reusable. You can Ctrl+F a transcript to find a specific moment, paste it into an AI tool to summarize it, or repurpose it into a blog post — all far faster than scrubbing through video.",
  },
  {
    q: "Is the converted transcript accurate?",
    a: "Accuracy depends on the source captions. Manually created captions (added by the video's creator) are typically very accurate; auto-generated captions are usually good but can occasionally misread names or technical terms.",
  },
  {
    q: "Can I convert a YouTube video to a transcript in another language?",
    a: "Yes. If the video has captions in multiple languages, the tool detects them and returns the transcript in the available caption language, no translation involved.",
  },
];

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: "https://www.savefromnet.fun",
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "YouTube to Transcript",
      item: "https://www.savefromnet.fun/youtube-to-transcript",
    },
  ],
};

export default function YouTubeToTranscriptPage() {
  return (
    <main className="min-h-screen bg-zinc-950 text-white">
      <Navbar />

      <JsonLd data={breadcrumbJsonLd} />
      <JsonLd data={softwareAppJsonLd} />

      <PSeoHero
        badge="Free Converter · No Sign-Up · Instant"
        title="YouTube to Transcript"
        subtitle="Turn any public YouTube video into clean, accurate text in seconds. Paste a link below and get the full transcript back instantly — no software, no account, completely free."
      />

      <div className="bg-white text-center text-xs text-slate-400">
        Last updated {lastUpdated}
      </div>

      <ContentBlock
        heading="3 Ways to Turn a YouTube Video Into a Transcript"
        paragraphs={[
          "There are a few ways to get from a YouTube video to a transcript. Here's how they actually compare.",
        ]}
        listTitle="Compare the options"
        list={[
          "This converter — paste a link, get clean text with copy, TXT, timestamped TXT and SRT export in one step. Takes seconds, works on any device, nothing to install.",
          "YouTube's built-in transcript panel — click ⋯ → Show transcript under any video. Fine for reading along, but the timestamps are mixed into every line and there's no direct download.",
          "Manual transcription — typing out what you hear as you watch. Accurate if done carefully, but by far the slowest option for anything longer than a couple of minutes.",
        ]}
      />

      <ContentBlock
        heading="How Transcript Extraction Actually Works"
        paragraphs={[
          "A YouTube transcript isn't generated by this tool listening to the video — it's read directly from the caption track YouTube already stores for that video. Every public YouTube video with captions has one of two kinds: manually written captions the creator uploaded, or auto-generated captions produced by YouTube's own speech recognition when the video was published.",
          "This tool fetches that existing caption track's timed text data and reformats it — into plain copy-paste text, into a timestamped version for reference, or into SRT format for use as actual subtitles. Because it's reading data that already exists rather than re-transcribing audio, results come back in seconds regardless of video length, and accuracy is exactly as good as the source captions already are.",
          "This also explains the one real limitation: a video with no captions at all — creator-provided or auto-generated — has no transcript to extract. That's a property of the video on YouTube's side, not something any transcript tool can work around.",
        ]}
      />

      <Citations />

      <ContentBlock
        heading="What People Do With a YouTube Transcript"
        paragraphs={[
          "Once a video is text, it becomes searchable, quotable and reusable in ways the video itself isn't. See how different people put it to work:",
        ]}
        listTitle="Popular uses"
        list={[
          "Students — turn lectures into searchable notes",
          "Content creators — repurpose a video into a blog post or social captions",
          "Researchers — cite interviews and talks with accurate, timestamped text",
          "Marketers & SEO teams — mine competitor videos for keywords and FAQs",
          "Anyone using AI — paste a transcript into ChatGPT or Claude to summarize it",
        ]}
      />

      <Features />

      <HowItWorks />

      <FAQ
        faqs={faqs}
        title="YouTube to Transcript — FAQ"
        description="Common questions about converting a YouTube video into a transcript."
      />

      <section className="bg-slate-50 pb-24">
        <div className="mx-auto max-w-4xl px-6 text-center text-sm text-slate-500">
          Looking for something more specific? See transcripts{" "}
          <Link href="/youtube-transcript-for" className="text-green-600 underline">
            by use case
          </Link>
          , transcripts{" "}
          <Link href="/youtube-transcript-in" className="text-green-600 underline">
            by language
          </Link>
          , or export formats like{" "}
          <Link href="/tools/youtube-to-srt" className="text-green-600 underline">
            SRT
          </Link>{" "}
          and{" "}
          <Link href="/tools/youtube-transcript-to-pdf" className="text-green-600 underline">
            PDF
          </Link>
          .
        </div>
      </section>

      <CTA />
    </main>
  );
}
